#! /bin/bash
#
# Builds a docker image using docker-compose.
# Wraps running rake, bundler, rspec and cucumber.
# (requires docker and docker-compose to run)
#

function usage {
    echo "usage: $0 [OPTIONS]:"
    echo ""
    echo " build:      Build all images (app and db)"
    echo " run:        Run the app on the latest container"
    echo " clean:      Stop and removes all containers"
    echo ""
    echo " help:       Print this message"
    echo ""
}

function check_deps {
    # Check dependencies.
    command -v docker > /dev/null 2>&1 || { echo >&2 "I require '${DOCKER}', but it's not installed.  Aborting."; exit 1; }
    command -v docker-compose > /dev/null 2>&1 || { echo >&2 "I require '${DOCKER_COMPOSE}', but it's not installed.  Aborting."; exit 1; }
    return 0
}

function build {
    docker-compose build
}

function run {
    docker-compose up
}

function _exec {
    docker-compose run web "$@"
}

function clean {
    CONTAINERS=$(docker ps -a -q)
    if [[ -n $CONTAINERS ]]
    then
        sudo docker stop $CONTAINERS
        sudo docker rm $CONTAINERS
    fi
}

if check_deps; then
    if [[ $1 == build ]]; then build;
    elif [[ $1 == run ]]; then run;
    elif [[ $1 == clean ]]; then clean;
    elif [[ $1 == exec ]]; then
        shift
        _exec "$@"
    else { echo ""; echo "Error: invalid argument: "$1; echo ""; usage; exit 1; }
    fi
fi
