require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.


RSpec.describe AtendimentosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Atendimento. As you add validations to Atendimento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryGirl.build(:atendimento).attributes
  end

  let(:valid_old_atendimento) do
    FactoryGirl.build(:atendimento, :old).attributes
  end

  let(:valid_non_accepted) do
    FactoryGirl.build(:atendimento, :rejected).attributes
  end

  let(:invalid_attributes) do
    FactoryGirl.build(:atendimento, :invalid).attributes
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AtendimentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    sign_in FactoryGirl.build(:user, :admin_user)
  end

  describe "GET #index" do
    before (:each) do
      sign_in FactoryGirl.create(:user, :estagiario_user)
    end
    it "assigns all atendimentos as @atendimentos" do
      atendimento = Atendimento.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:atendimentos)).to eq([atendimento])
    end

    it "assigns all atendimentos as @atendimentos (except old atendimentos)" do
      atendimento = Atendimento.create! valid_attributes
      old_atendimento = Atendimento.create! valid_old_atendimento
      get :index, {}, valid_session
      expect(assigns(:atendimentos)).to eq([atendimento])
    end

    it "assigns all atendimentos as @atendimentos (except non accepted)" do
      atendimento = Atendimento.create! valid_attributes
      non_accepted_atendimento = Atendimento.create! valid_non_accepted
      get :index, {}, valid_session
      expect(assigns(:atendimentos)).to eq([atendimento])
    end

    it "assigns all atendimentos as @atendimentos (except already attended)" do
      atendimento = Atendimento.create! valid_attributes
      already_attended_atendimento = Atendimento.create! valid_attributes
      already_attended_atendimento.stubs(:estagiario).returns(FactoryGirl.build(:estagiario))
      Atendimento.stubs(:where).returns([atendimento, already_attended_atendimento])
      get :index, {}, valid_session
      expect(assigns(:atendimentos)).to eq([atendimento])
    end
  end

  describe "GET #my-cases" do
    before (:each) do
      sign_in FactoryGirl.create(:user, :estagiario_user)
    end

    it "assigns specific atendimentos as @atendimentos" do
      atendimento = Atendimento.create! valid_attributes
      Atendimento.stubs(:all_for).returns([atendimento])
      get :my_cases, valid_session
      expect(assigns(:atendimentos)).to eq([atendimento])
      atendimento.destroy
    end
  end


  describe "GET #show" do
    it "assigns the requested atendimento as @atendimento" do
      atendimento = Atendimento.create! valid_attributes
      get :show, {:id => atendimento.to_param}, valid_session
      expect(assigns(:atendimento)).to eq(atendimento)
    end
  end

  describe "GET #new" do
    it "assigns a new atendimento as @atendimento" do
      get :new, {}, valid_session
      expect(assigns(:atendimento)).to be_a_new(Atendimento)
    end
  end

  describe "GET #edit" do
    it "assigns the requested atendimento as @atendimento" do
      atendimento = Atendimento.create! valid_attributes
      get :edit, {:id => atendimento.to_param}, valid_session
      expect(assigns(:atendimento)).to eq(atendimento)
    end
  end

  describe "POST #create" do
    before (:each) do
      sign_in FactoryGirl.create(:user, :estagiario_user)
    end
    context "with valid params" do
      it "creates a new Atendimento" do
        expect {
          post :create, {:atendimento => valid_attributes}, valid_session
        }.to change(Atendimento, :count).by(1)
      end

      it "assigns a newly created atendimento as @atendimento" do
        post :create, {:atendimento => valid_attributes}, valid_session
        expect(assigns(:atendimento)).to be_a(Atendimento)
        expect(assigns(:atendimento)).to be_persisted
      end

      it "redirects to the created atendimento" do
        post :create, {:atendimento => valid_attributes}, valid_session
        expect(response).to redirect_to(Atendimento.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved atendimento as @atendimento" do
        post :create, {:atendimento => invalid_attributes}, valid_session
        expect(assigns(:atendimento)).to be_a_new(Atendimento)
      end

      it "re-renders the 'new' template" do
        post :create, {:atendimento => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    before (:each) do
      sign_in FactoryGirl.create(:user, :estagiario_user)
    end
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested atendimento" do
        atendimento = Atendimento.create! valid_attributes
        put :update, {:id => atendimento.to_param, :atendimento => new_attributes}, valid_session
        atendimento.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested atendimento as @atendimento" do
        atendimento = Atendimento.create! valid_attributes
        put :update, {:id => atendimento.to_param, :atendimento => valid_attributes}, valid_session
        expect(assigns(:atendimento)).to eq(atendimento)
      end

      it "redirects to the atendimento" do
        atendimento = Atendimento.create! valid_attributes
        put :update, {:id => atendimento.to_param, :atendimento => valid_attributes}, valid_session
        expect(response).to redirect_to(atendimento)
      end
    end

    context "with invalid params" do
      it "assigns the atendimento as @atendimento" do
        atendimento = Atendimento.create! valid_attributes
        put :update, {:id => atendimento.to_param, :atendimento => invalid_attributes}, valid_session
        expect(assigns(:atendimento)).to eq(atendimento)
      end

      it "re-renders the 'edit' template" do
        atendimento = Atendimento.create! valid_attributes
        put :update, {:id => atendimento.to_param, :atendimento => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

end
