require 'rails_helper'
require 'mocha'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CalourosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Calouro. As you add validations to Calouro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryGirl.attributes_for(:calouro)
  end

  let(:invalid_attributes) do
    FactoryGirl.attributes_for(:calouro, :calouro_invalid)
  end

  let(:new_attributes) do
    FactoryGirl.attributes_for(:calouro, :new_calouro)
  end

  before :each do
      @user = FactoryGirl.build :user
      User.stubs(:find).returns(@user)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CalourosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all calouros as @calouros" do
      calouro = Calouro.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:calouros)).to eq([calouro])
    end
  end

  describe "GET #show" do
    it "assigns the requested calouro as @calouro" do
      calouro = Calouro.create! valid_attributes
      get :show, {:id => calouro.to_param}, valid_session
      expect(assigns(:calouro)).to eq(calouro)
    end
  end

  describe "GET #new" do
    it "assigns a new calouro as @calouro" do
      get :new, {}, valid_session
      expect(assigns(:calouro)).to be_a_new(Calouro)
    end
  end

  describe "GET #edit" do
    it "assigns the requested calouro as @calouro" do
      calouro = Calouro.create! valid_attributes
      get :edit, {:id => calouro.to_param}, valid_session
      expect(assigns(:calouro)).to eq(calouro)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Calouro" do
        expect {
          post :create, {:calouro => valid_attributes}, valid_session
        }.to change(Calouro, :count).by(1)
      end

      it "assigns a newly created calouro as @calouro" do
        post :create, {:calouro => valid_attributes}, valid_session
        expect(assigns(:calouro)).to be_a(Calouro)
        expect(assigns(:calouro)).to be_persisted
      end

      it "redirects to the created calouro" do
        post :create, {:calouro => valid_attributes}, valid_session
        expect(response).to redirect_to(Calouro.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved calouro as @calouro" do
        post :create, {:calouro => invalid_attributes}, valid_session
        expect(assigns(:calouro)).to be_a_new(Calouro)
      end

      it "re-renders the 'new' template" do
        post :create, {:calouro => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      it "updates the requested calouro" do
        calouro = Calouro.create! valid_attributes
        put :update, {:id => calouro.to_param, :calouro => new_attributes}, valid_session
        calouro.reload
        expect(calouro.nome).to eq(new_attributes[:nome])
      end

      it "assigns the requested calouro as @calouro" do
        calouro = Calouro.create! valid_attributes
        put :update, {:id => calouro.to_param, :calouro => valid_attributes}, valid_session
        expect(assigns(:calouro)).to eq(calouro)
      end

      it "redirects to the calouro" do
        calouro = Calouro.create! valid_attributes
        put :update, {:id => calouro.to_param, :calouro => valid_attributes}, valid_session
        expect(response).to redirect_to(calouro)
      end
    end

    context "with invalid params" do
      it "assigns the calouro as @calouro" do
        calouro = Calouro.create! valid_attributes
        put :update, {:id => calouro.to_param, :calouro => invalid_attributes}, valid_session
        expect(assigns(:calouro)).to eq(calouro)
      end

      it "re-renders the 'edit' template" do
        calouro = Calouro.create! valid_attributes
        put :update, {:id => calouro.to_param, :calouro => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested calouro" do
      calouro = Calouro.create! valid_attributes
      expect {
        delete :destroy, {:id => calouro.to_param}, valid_session
      }.to change(Calouro, :count).by(-1)
    end

    it "redirects to the calouros list" do
      calouro = Calouro.create! valid_attributes
      delete :destroy, {:id => calouro.to_param}, valid_session
      expect(response).to redirect_to(calouros_url)
    end
  end

end
