require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RelatosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Relato. As you add validations to Relato, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RelatosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before (:each) do
    sign_in FactoryGirl.create(:user, :admin_user) 
  end

  describe "GET #index" do
    it "assigns all relatos as @relatos" do
      relato = Relato.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:relatos)).to eq([relato])
    end
  end

  describe "GET #show" do
    it "assigns the requested relato as @relato" do
      relato = Relato.create! valid_attributes
      get :show, {:id => relato.to_param}, valid_session
      expect(assigns(:relato)).to eq(relato)
    end
  end

  describe "GET #new" do
    it "assigns a new relato as @relato" do
      get :new, {}, valid_session
      expect(assigns(:relato)).to be_a_new(Relato)
    end
  end

  describe "GET #edit" do
    it "assigns the requested relato as @relato" do
      relato = Relato.create! valid_attributes
      get :edit, {:id => relato.to_param}, valid_session
      expect(assigns(:relato)).to eq(relato)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Relato" do
        expect {
          post :create, {:relato => valid_attributes}, valid_session
        }.to change(Relato, :count).by(1)
      end

      it "assigns a newly created relato as @relato" do
        post :create, {:relato => valid_attributes}, valid_session
        expect(assigns(:relato)).to be_a(Relato)
        expect(assigns(:relato)).to be_persisted
      end

      it "redirects to the created relato" do
        post :create, {:relato => valid_attributes}, valid_session
        expect(response).to redirect_to(Relato.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved relato as @relato" do
        post :create, {:relato => invalid_attributes}, valid_session
        expect(assigns(:relato)).to be_a_new(Relato)
      end

      it "re-renders the 'new' template" do
        post :create, {:relato => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested relato" do
        relato = Relato.create! valid_attributes
        put :update, {:id => relato.to_param, :relato => new_attributes}, valid_session
        relato.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested relato as @relato" do
        relato = Relato.create! valid_attributes
        put :update, {:id => relato.to_param, :relato => valid_attributes}, valid_session
        expect(assigns(:relato)).to eq(relato)
      end

      it "redirects to the relato" do
        relato = Relato.create! valid_attributes
        put :update, {:id => relato.to_param, :relato => valid_attributes}, valid_session
        expect(response).to redirect_to(relato)
      end
    end

    context "with invalid params" do
      it "assigns the relato as @relato" do
        relato = Relato.create! valid_attributes
        put :update, {:id => relato.to_param, :relato => invalid_attributes}, valid_session
        expect(assigns(:relato)).to eq(relato)
      end

      it "re-renders the 'edit' template" do
        relato = Relato.create! valid_attributes
        put :update, {:id => relato.to_param, :relato => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested relato" do
      relato = Relato.create! valid_attributes
      expect {
        delete :destroy, {:id => relato.to_param}, valid_session
      }.to change(Relato, :count).by(-1)
    end

    it "redirects to the relatos list" do
      relato = Relato.create! valid_attributes
      delete :destroy, {:id => relato.to_param}, valid_session
      expect(response).to redirect_to(relatos_url)
    end
  end

end
