require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe VareirosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Vareiro. As you add validations to Vareiro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    FactoryGirl.attributes_for(:vareiro)
  end

  let(:invalid_attributes) do
    FactoryGirl.attributes_for(:vareiro, :vareiro_invalid)
  end

  let(:new_attributes) do
    FactoryGirl.attributes_for(:vareiro, :new_vareiro)
  end

  before :each do
      @user = FactoryGirl.build :user
      User.stubs(:find).returns(@user)
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VareirosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all vareiros as @vareiros" do
      vareiro = Vareiro.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:vareiros)).to eq([vareiro])
    end
  end

  describe "GET #show" do
    it "assigns the requested vareiro as @vareiro" do
      vareiro = Vareiro.create! valid_attributes
      get :show, {:id => vareiro.to_param}, valid_session
      expect(assigns(:vareiro)).to eq(vareiro)
    end
  end

  describe "GET #new" do
    it "assigns a new vareiro as @vareiro" do
      get :new, {}, valid_session
      expect(assigns(:vareiro)).to be_a_new(Vareiro)
    end
  end

  describe "GET #edit" do
    it "assigns the requested vareiro as @vareiro" do
      vareiro = Vareiro.create! valid_attributes
      get :edit, {:id => vareiro.to_param}, valid_session
      expect(assigns(:vareiro)).to eq(vareiro)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Vareiro" do
        expect {
          post :create, {:vareiro => valid_attributes}, valid_session
        }.to change(Vareiro, :count).by(1)
      end

      it "assigns a newly created vareiro as @vareiro" do
        post :create, {:vareiro => valid_attributes}, valid_session
        expect(assigns(:vareiro)).to be_a(Vareiro)
        expect(assigns(:vareiro)).to be_persisted
      end

      it "redirects to the created vareiro" do
        post :create, {:vareiro => valid_attributes}, valid_session
        expect(response).to redirect_to(Vareiro.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved vareiro as @vareiro" do
        post :create, {:vareiro => invalid_attributes}, valid_session
        expect(assigns(:vareiro)).to be_a_new(Vareiro)
      end

      it "re-renders the 'new' template" do
        post :create, {:vareiro => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      it "updates the requested vareiro" do
        vareiro = Vareiro.create! valid_attributes
        put :update, {:id => vareiro.to_param, :vareiro => new_attributes}, valid_session
        vareiro.reload
        expect(vareiro.nome).to eq(new_attributes[:nome])
      end

      it "assigns the requested vareiro as @vareiro" do
        vareiro = Vareiro.create! valid_attributes
        put :update, {:id => vareiro.to_param, :vareiro => valid_attributes}, valid_session
        expect(assigns(:vareiro)).to eq(vareiro)
      end

      it "redirects to the vareiro" do
        vareiro = Vareiro.create! valid_attributes
        put :update, {:id => vareiro.to_param, :vareiro => valid_attributes}, valid_session
        expect(response).to redirect_to(vareiro)
      end
    end

    context "with invalid params" do
      it "assigns the vareiro as @vareiro" do
        vareiro = Vareiro.create! valid_attributes
        put :update, {:id => vareiro.to_param, :vareiro => invalid_attributes}, valid_session
        expect(assigns(:vareiro)).to eq(vareiro)
      end

      it "re-renders the 'edit' template" do
        vareiro = Vareiro.create! valid_attributes
        put :update, {:id => vareiro.to_param, :vareiro => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested vareiro" do
      vareiro = Vareiro.create! valid_attributes
      expect {
        delete :destroy, {:id => vareiro.to_param}, valid_session
      }.to change(Vareiro, :count).by(-1)
    end

    it "redirects to the vareiros list" do
      vareiro = Vareiro.create! valid_attributes
      delete :destroy, {:id => vareiro.to_param}, valid_session
      expect(response).to redirect_to(vareiros_url)
    end
  end

end
